# ASPCUD optimization criteria for experimental
$aspcud_criteria = '-count(down),-count(changed,APT-Release:=/experimental/),-removed,-changed,-new';

# Disable check space, as the heuristic used seems wrong at least from some packages
$check_space = 0;

# Don't let sbuild try and create chroots itself using mmdebstrap
$unshare_mmdebstrap_auto_create=0;

# Define build directory for --chroot-mode=unshare, otherwise /tmp is used
$unshare_tmpdir_template='/srv/buildd/tmp.sbuild.XXXXXXXXXX';

# Use a predictible build path (see Bug#1034424)
$build_path='/build/reproducible-path';

# Don't clean the apt cache in trixie
$clean_apt_cache = 0;

$external_commands = {
  'chroot-setup-commands' => [
    ['bash', '-c', 'hostname > /etc/hostname'],
  ],
};

$build_environment = {
  # 'QTEST_FUNCTION_TIMEOUT' => '600000',
};

$individual_stalled_pkg_timeout->{'lz4-java'} = 800;
$individual_stalled_pkg_timeout->{'openjdk-21'} = 800;
$individual_stalled_pkg_timeout->{'openjdk-25'} = 800;
