package config;

use strict;
use warnings;

our %preupload = (
    # Check changes file for valid signatures.
    changes => [
        '/usr/share/dupload/openpgp-check %1',
    ],
    sourcepackage => [] ,
    file => [],
    deb => [],
    package => [],
    host => [],
);

our %postupload = (
    changes => [],
    sourcepackage => [],
    file => [],
    deb => [],
    package => [],
    host => [],
);

our %cfg;

my $keyrings_buildd = [
        '/home/buildd/.gnupg/pubring.gpg',
];

# rsync upload to ssh.upload.debian.org
$cfg{'rsync-ftp-master'} = {
        method => "rsync",
        login => "uploader",
        fqdn => "deb.internal.apernet.io",
        incoming => "/srv/repos/builds2/incoming/",
        keyrings => $keyrings_buildd,
        # files pass on to dinstall on ftp-master which sends emails itself
        dinstall_runs => 1,
};

# Don't remove the following line.  Perl needs it.
1;

